### PR TITLE
Output as Nix expression

### PR DESCRIPTION
**Pull request by 8084**
In short,

```
$ nix-prefetch-github --nix seppeljordan nix-prefetch-github
let
  pkgs = import <nixpkgs> {};
in
  pkgs.fetchFromGitHub {
    owner = "seppeljordan";
    repo = "nix-prefetch-github";
    rev = "f71616bde96da27329e4a6db4a339381472f2e36";
    sha256 = "1vf5i3s9ql9cr37smbqyqdrpiympjxx3kmwn6xv9h2fn5jyiwh8y";
  };
```

Also, I've tried to make `--hash-only` and `--nix` mutually exclusive, but I couldn't find an easy way to achieve it.

I.e. [this](https://stackoverflow.com/questions/37310718/mutually-exclusive-option-groups-in-python-click) method does not work properly with flags defined using slash (`--hash-only/--no-hash-only` in this case). It makes `--nix` and `--no-hash-only` mutually exclusive too.

May I ask what was the motivation for adding `--no-hash-only` flag?

### CODE REVIEW

**Comment by seppeljordan** [comment]
Hi @8084,

thanks for your submission, really appreciate it.  It will gladly merge this after a couple of things are more clear.

1. There are a couple of tests with this python package.  It would be great if the new flag could be tested somehow.  For example, we could check if after passing the flag, the output of the program is still understood by `json.loads` or something similar.
2. The `--hash-only` flag is there to calculate the hash for `fetchFromGitHub` only without prefetching the derivation.  I think it would be possible to make all combinations of `--nix` and `--hash-only/--no-hash-only` work together nicely.

So these are the things I wanted to bring up.  Would you  care to implement 1 or more of these in your PR?  If you don't want to that's fine.  I can make the adjustments myself if necessary.

**Comment by 8084** [comment]
> 1. There are a couple of tests with this python package.  It would be great if the new flag could be tested somehow. 

OK, I think I'll add a test that asserts that the output with `--nix` is a valid nix expression.

> 2. The `--hash-only` flag is there to calculate the hash for `fetchFromGitHub` only without prefetching the derivation.

I was asking about `--no-hash-only`. Why having it if it is the default?

> I think it would be possible to make all combinations of `--nix` and `--hash-only/--no-hash-only` work together nicely.

Yes, it is surely possible, but it looks like `click` does not offer the ability to define mutually exclusive flags. So the only way is to process these flags by hand. I'll do it.

**Comment by seppeljordan** [comment]
> > 1. There are a couple of tests with this python package.  It would be great if the new flag could be tested somehow.
> 
> OK, I think I'll add a test that asserts that the output with `--nix` is a valid nix expression.
> 
> > 1. The `--hash-only` flag is there to calculate the hash for `fetchFromGitHub` only without prefetching the derivation.
> 
> I was asking about `--no-hash-only`. Why having it if it is the default?

The `--no-hash-only` is there to reenable the prefetching if it was disabled by a previous flag.  Use case would be that someone wrote a wrapper script that can pass options to `nix-prefetch-github`.  With a flag like this the user of the wrapper script could reenable prefetching without changing the wrapper script.
 
> > I think it would be possible to make all combinations of `--nix` and `--hash-only/--no-hash-only` work together nicely.
> 
> Yes, it is surely possible, but it looks like `click` does not offer the ability to define mutually exclusive flags. So the only way is to process these flags by hand. I'll do it.

I think we have a misunderstanding here.  I think the all the flags COULD play nicely together, no need for exclusivity (IMHO).

**Comment by 8084** [comment]
>  With a flag like this the user of the wrapper script could reenable prefetching without changing the wrapper script.

Makes sense. Should I add --no-nix then?

> I think we have a misunderstanding here. I think the all the flags COULD play nicely together, no need for exclusivity (IMHO).

OK. What should be the output of:

1. `nix-prefetch-github --nix --hash-only`
2. `nix-prefetch-github --nix --no-hash-only`
3. `nix-prefetch-github --hash-only --nix`
4. `nix-prefetch-github --no-hash-only --nix` ?

**Comment by seppeljordan** [comment]
> > With a flag like this the user of the wrapper script could reenable prefetching without changing the wrapper script.
> 
> Makes sense. Should I add --no-nix then?
> 
> > I think we have a misunderstanding here. I think the all the flags COULD play nicely together, no need for exclusivity (IMHO).
> 
> OK. What should be the output of:
> 
>     1. `nix-prefetch-github --nix --hash-only`
> 
>     2. `nix-prefetch-github --nix --no-hash-only`
> 
>     3. `nix-prefetch-github --hash-only --nix`
> 
>     4. `nix-prefetch-github --no-hash-only --nix` ?

OK, I think I found the root cause of the misunderstanding.  The flags `--hash-only` and `--no-hash-only` do not change the output of the program, but only if the specified github source should be fetched into nix store while determining the has for `fetchFromGitHub` function.

**Comment by 8084** [comment]
My bad :) I should've run it at least once with this flag.

**Comment by seppeljordan** [comment]
No worries.  I admit that the flags name is really confusing.

**Comment by seppeljordan** [comment]
Thank you very much.

**Pull request merged**
