### PR TITLE
Don't cripple sri hashes

### PR DESCRIPTION
**Pull request by SuperSandro2000**
relates to #49

### CODE REVIEW

**Comment by hraban** [comment]
While we're at it I would also vote to name the field `hash` not `sha256`.

**Comment by seppeljordan** [comment]
@SuperSandro2000 Thank you for your contribution. I can merge this as soon as the tests pass.

**Comment by hraban** [comment]
> While we're at it I would also vote to name the field `hash` not `sha256`.

or `narHash`, in accordance with flake lock files, although I'll be honest I don't see how this is a nar. Is it because the files are extracted to a store path and a nar is built from that and then hashed?

**Comment by SuperSandro2000** [comment]
Fixed the tests

**Comment by seppeljordan** [comment]
@SuperSandro2000 thanks. I had to edit the issue description since the issue #49 is not completely resolved.

**Pull request merged**
